
name: RemoteNestedWorkflow

on:
  repository_dispatch:
    types: [test]
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      home:
        description: 'location'
        required: false
        default: 'The Octoverse'

jobs:
  nested-workflow-job:
    runs-on: ubuntu-latest
    name: Remote Nested Job
    steps:
    - run: |
        echo "Salute ${{ github.event.inputs.name }} from ${{ github.event.inputs.home }}"
